# Generated by Django 4.0 on 2021-12-24 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of creation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='booked_from',
            field=models.DateTimeField(verbose_name='From:'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='booked_till',
            field=models.DateTimeField(verbose_name='Until:'),
        ),
    ]
