# Generated by Django 4.0 on 2021-12-25 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reservation_created_on_alter_reservation_booked_from_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(check=models.Q(('booked_from__gte', datetime.datetime(2021, 12, 25, 19, 33, 40, 793856))), name='valid_booking_time'),
        ),
    ]
